[[server]]

listen = ["127.0.0.1:8100", "192.168.1.2:8100"]

[[server.match]]

uri = "/api"

forward = [
    { address = "127.0.01:7070", weight = 2 },
    { address = "127.0.01:7071", weight = 1 },
    { address = "127.0.01:7073", weight = 3 },
]

request.headers.forwarded = { extend = true }
# request.headers.forwarded = { by = "custom_name" }

response.headers.via = { extend = true }
response.headers.server = { override = true, version = false }

[[server.match]]

uri = "/"
serve = "/website"
